added a homework
iAmGladToSeeYou/Yauhen-Haurylenka-html pull request #5
Opened 2019-04-17 10:36 UTC by iAmGladToSeeYou

Напишите пожалуйста ошибки и недочеты. Советы по улучшению.

2019-04-17 12:06 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Prototype.js
> +SunPlanet.prototype.constructor = Planet;
Что должно быть в конструкторе?

2019-04-17 12:07 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +  this._radiusEarth = 6371;
Странно что AllPlanet знает о _radiusEarth

2019-04-17 12:08 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +function SunPlanet(name, radius, period) {
SunPlanet это планета Солнце? странно

2019-04-17 12:09 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +  this._earthPeriod = 365;
как _earthPeriod относится SunPlanet

2019-04-17 12:09 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +    var finish;
переменную нужно инитать каким-то значением

2019-04-17 12:11 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +    return pSizeMoreThenEarth.call(this);
Зачем возвращать метод родителя? думаю стоит просто вызывать.

2019-04-17 12:16 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Prototype.js
> +SunPlanet.prototype.sizeMoreThenEarth = function() {
тут нет наследования, это копирование

2019-04-17 12:17 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/es6class.js
> +  sizeMoreThenEarth() {
где наследование?

2019-04-17 12:20 UTC, FE-2019-TRAINERS commented
+ в прототипном и классах применить коменты от функционального

2019-04-17 12:21 UTC, FE-2019-TRAINERS requested changes
Request changes

2019-04-17 14:23 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Prototype.js
> +SunPlanet.prototype.constructor = Planet;
Исправил. Изначальное название было Planet, потом изменил на SunPlanet. Забыл изменить в этом месте

2019-04-17 14:24 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +  this._radiusEarth = 6371;
AllPlanet принимает в себя радиус любой планеты и сравнивает его с радиусом Земли

2019-04-17 14:25 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +function SunPlanet(name, radius, period) {
Переименовал для лучшего понимания. Планеты солнечной системы)

2019-04-17 14:26 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +  this._earthPeriod = 365;
_earthPeriod - период вращения вокруг солнца. Этот конструктор принимает period - период вращения других планет и сравнивает во сколько раз год на планете Земля больше или меньше чем на другой планете.

2019-04-17 14:27 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +    var finish;
Если я правильно понял, то исправил

2019-04-17 14:28 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +    return pSizeMoreThenEarth.call(this);
если без возврата вызвать этот метод, то возвращает undefined

2019-04-17 14:29 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Prototype.js
> +SunPlanet.prototype.sizeMoreThenEarth = function() {
В задании нужно было переопределить метод. Переопределил родительский метод который сравнивал радиусы... теперь сравнивает диаметры )

2019-04-17 14:30 UTC, iAmGladToSeeYou commented on Task6 - inheritance/es6class.js
> +  sizeMoreThenEarth() {
переопределил метод. Точно так же как и в прототипном. Теперь сравнивает диаметры

2019-04-22 12:39 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +    var finish;
Еще важен тип твоего значения, если собираешься вернуть строку, то и инитать нужно строковым значением.

2019-04-22 12:58 UTC, FE-2019-TRAINERS commented on Task6 - inheritance/Functional.js
> +    return pSizeMoreThenEarth.call(this);
Тут наверное я не правильно написал. В общем случае тебе нужно просто вызывать метод родителя. Он может делать любые штуки (не обязательно что-то возвращать, например логировать результат). А далее надо смотреть на конкретную реализацию, т.к. ты ожидаешь что метод pSizeMoreThenEarth что-то вернет, то можно создать какую-то переменную и записать в нее результат. А затем уже что-то делать с этим результатом.
this.sizeMoreThenEarth = function () {
      this.run();
      var res = pSizeMoreThenEarth.call(this);
      // do smth with res
    };

2019-04-22 13:03 UTC, FE-2019-TRAINERS commented
В целом ок.

2019-04-26 07:34 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +    return pSizeMoreThenEarth.call(this);
Вроде все понял и исправил

2019-04-26 07:34 UTC, iAmGladToSeeYou commented on Task6 - inheritance/Functional.js
> +    var finish;
Понял, исправил

2019-04-26 09:20 UTC, FE-2019-TRAINERS approved these changes
good job

2019-04-28 19:54 UTC, merged